


POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "Nothing is Impossible",
    "author": "Hard Work",
    "url": "github.com",
    "likes": 100,
    "user": "61fa77187dd7ee95d85b7cdd"
}


